### ISSUE TITLE
why this sync history repeated multiple times? 

### ISSUE THREAD

**Issue by siddhant3030** [DalgoT4D/webapp#1079]
This is for SHRI - On the log page some of the rows are being repeated. 

<img width="1448" alt="Screenshot 2024-07-31 at 1 13 13 AM" src="https://github.com/user-attachments/assets/f0c137b1-0943-4134-9bf5-ebcf9632917b">

**Comment by fatchat** [comment]
looks like a bug
can you include the client in all such bug reports please

**Comment by siddhant3030** [comment]
> looks like a bug can you include the client in all such bug reports please

Done

**Comment by himanshudube97** [comment]
Possible Cause -The issue is with the offset that we are sending here. Its 1, so for every load more the db is skipping just one row. 
Solution- we can send the offset from frontend in mulitple of 3 (3, 6, 9), so db will skip the already fetched entries. 
<img width="349" alt="image" src="https://github.com/user-attachments/assets/512b0b31-76a9-46c2-9ccf-7cb8041cf4db">
