### ISSUE TITLE
Rename column does not behave as expected

### ISSUE THREAD

**Issue by ashwinit4d** [DalgoT4D/webapp#1099]
**Describe the bug**
Rename Column function requires you to Add a column in order to rename it. The initial form values are considered void. Check screenshot

**To Reproduce**
1. Select a table
2. Select function "Rename Column"
3. update the column name and the new column name
4. Can view the error - Atleast one column name to be added
5. Now Add column
6. update the column name and new column name
7. it works

**Expected behavior**
Once you update the Rename table form (without adding column), it should take the input values and save the operation
After the first 3 steps listed above the update function should have worked.

**Screenshots**

<img width="1470" alt="Screenshot 2024-08-02 at 6 05 04 PM" src="https://github.com/user-attachments/assets/a315383e-a8f5-4069-9097-bfc4384a8ee5">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by fatchat** [comment]
hi ashwini could you clarify...

- the "steps to reproduce" say that selecting the operation after selecting a source/model will show the error
- but in the initial description you mention "initial form values" , what are these? the form loads with no columns selected
- in your screenshot it looks like you are trying to rename "MRN" to "MRNO" which somehow triggered the red error message, but some context must be missing because i did basic renaming during the workshop and i know the operation isn't completely broken

you also mentioned "once you update the form" is it possible you initially selected a column to rename, clicked Save, then clicked Back, then clicked Save again? or something like that

**Comment by ashwinit4d** [comment]
Updated the "steps to reproduce the bug" and the expected behavior

**Comment by fatchat** [comment]
@mdshamoon wasn't this fixed as part of https://github.com/DalgoT4D/webapp/pull/1075

**Comment by mdshamoon** [comment]
Yes @fatchat. I think the issue was opened before our deployment this weekend. I just checked and it is fixed now.

**Comment by fatchat** [comment]
@ashwinit4d can you verify and close if it is fixed thank you

**Comment by ashwinit4d** [comment]
This is working now.
