### ISSUE TITLE
Add new column and then try to summarize it after accepting schema changes, and resyncing

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#1213]
"Seems its not updating the new column, Error is as follows :

(psycopg2.errors.UndefinedColumn) column ""description"" does not exist LINE 1: SELECT Description ^ HINT: Perhaps you meant to reference the column ""worldometer_data.Description"". [SQL: SELECT Description FROM staging_sheets.worldometer_data LIMIT 500] (Background on this error at: https://sqlalche.me/e/14/f405)"

**Comment by Ishankoradia** [comment]
@nairabhishek73 this is not a schema change detection issue. You entered the query wrong 
 
In postgres if the column names have a starting letter captial you need to add quotes because postgres by default lowercases them 

This query works
`
SELECT "Description" FROM staging_sheets.worldometer_data LIMIT 500
`

**Comment by Ishankoradia** [comment]
Close it once you have rechecked

**Comment by nairabhishek73** [comment]
Thanks!
