### ISSUE TITLE
how to handle multiple sources

### ISSUE THREAD

**Issue by jakejh** [DalgoT4D/webapp#422]
A common paradigm I've seen is to have airbyte write to a separate bigquery dataset for each source. This setup then works well with dbt and the `source` function. I would prefer this to a single dataset for all sources, even if using a prefix to avoid name collisions.

I'd submitted a github issue about this previously, but can't find it.

**Comment by fatchat** [comment]
@siddhant3030 @Abhishek-N @Ishankoradia do you guys remember why we locked the destination schema to `staging` in the source-creation UI? 

as far as i recall we did this because our dbt code assumed it, there were no other reasons

we can very easily relax that requirement, i think it's just a UI change (make the destination schema editable)

any thoughts? else we'll do it this week

**Comment by jakejh** [comment]
Thanks! Based on my attempts just now, I'm still blocked [here](https://github.com/DalgoT4D/webapp/issues/421), but will test this new functionality when I can.
