### ISSUE TITLE
select dbt model to run on transformations page

### ISSUE THREAD

**Issue by fatchat** [DalgoT4D/webapp#435]

**Comment by Ishankoradia** [comment]
understand from swapneel and see if this should go in the platform or not. 
@nairabhishek73  will reach out and let us know.

**Comment by swapneelrane** [comment]
instead of a pre-defined list of dbt commands, having text boxes where we can enter the commands we want to run would be super helpful, as sometimes we just wanted to run or test specific models

this is how it looks like on dbt cloud:
![Image](https://github.com/DalgoT4D/webapp/assets/21273738/c823683d-c108-460f-8847-78e29597441e)

**Comment by nairabhishek73** [comment]
Hey @swapneelrane thanks for sharing here which current and past orgs this is relevant for. You had mentioned Dost and SNEHA.
Any other orgs?

**Comment by abikarmakar** [comment]
It would be helpful if I can run **selected models** or **select tags** on DALGO, rather than doing a complete DBT run.
