### ISSUE TITLE
Make warehouse details editable

### ISSUE THREAD

**Issue by swapneelrane** [DalgoT4D/webapp#450]
**Describe the bug**
I added Antarang BigQuery instance as a destiantion and was trying to change the load method to `GCS Staging` but the fields are all locked. This might be happening cause the connection is currently under sync.

**Expected behavior**
If source or destinations should not be edted when in use, then display a message and show the _Edit_ button disabled.

**Screenshots**

![Image](https://github.com/DalgoT4D/webapp/assets/21273738/ccf46376-db84-4625-b1e7-666d96670958)

**Comment by fatchat** [comment]
so... the non-editability is actually a feature not a bug, and has nothing to do with when a connection is running. 

and it's a feature not because we love it this way but because certain edits are hard to do... @Ishankoradia do you remember our reasoning? 

if i recall correctly, 

- we didn't want to allow changing of the warehouse type / the warehouse entity itself
- but we can enable editing certain warehouse parameters

right now i believe passwords are editable but nothing else

**Comment by Ishankoradia** [comment]
Currenly only the secrets (or passwords) are editable. As far as i remember that was our reasoning. 

But we can definitely make certain warehouse parameters editable
