### ISSUE TITLE
UI Transform: Cannot delete Tables

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#609]
https://jam.dev/c/6dfe5eb9-df2d-49f5-99b1-9b34dc6cbcc3

But pressing delete on the keyboard worked

**Comment by fatchat** [comment]
@Ishankoradia 

pressing delete on the keyboard worked because the message was picked up by the graphing library

clicking the button however sends a `DELETE` to our backend which does nothing (`transport_api.py:532` which looks correct)

can we do the following:
- if a node is a source_model node with no predecessors, 
- don't hit the API, and instead
- let the graphing library take care of node removal

if you agree with my assessment i.e. that there is no backend work, you can ask shamoon to do this

**Comment by Ishankoradia** [comment]
@fatchat  , this is an edge that our backend needs to handle. At the same line you pointed, we need to handle the case of when`operations == 0` for a model on the canvas (Nair faced this).

It works when you press delete button but re-surfaces as soon as you hit refresh graph. So we still need to remove it from our backend.

**Comment by Ishankoradia** [comment]
This should fix it - https://github.com/DalgoT4D/DDP_backend/pull/512

**Comment by fatchat** [comment]
@nairabhishek73 please have a look

**Comment by nairabhishek73** [comment]
Works!
