### ISSUE TITLE
Multiple or divide by float

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#708]
To generate 20% of a column I should be able to multiply by 0.2

**Comment by fatchat** [comment]
and that doesn't work?

**Comment by nairabhishek73** [comment]
No it asks me to enter an integer.
https://jam.dev/c/9528d6ec-c971-4dec-b807-2818120f51bf

**Comment by fatchat** [comment]
@mdshamoon we need the `Input` to take `float`s ... googling told me we can get this by passing a float value for `step` to the underlying `input` 

but TS isn't letting me add `step` to the `Input` component

**Comment by nairabhishek73** [comment]
Could we also get rid of the up and down button in that input box.

**Comment by fatchat** [comment]
yes it's annoying but it's part of the html component. if shamoon knows how to (without changing the type!) then yes otherwise not for now

(in future we could change the input type to a string and then validate separately)

**Comment by fatchat** [comment]
@nairabhishek73 for your review

**Comment by nairabhishek73** [comment]
Hi Its taking the input now but failed to create the table. Check- UI testiung org 6

**Comment by mdshamoon** [comment]
@fatchat I think this needs to be fixed from the backend. UI wise seems fine to me.

**Comment by nairabhishek73** [comment]
Do we know what the problem is now?

**Comment by fatchat** [comment]
@nairabhishek73 the original problem reported has been solved. what i saw in `ui-testing-org-6` was a column got renamed

one possibility is that two users were modifying the flow simultaneously, i.e. you and i, and we enter different column names somewhere

even if that is not the case i'd like to close this issue since the original bug has been fixed i.e. input not taking a float val

we should open a new issue when we observe the bug again
