### ISSUE TITLE
form validation

### ISSUE THREAD

**Issue by fatchat** [DalgoT4D/webapp#735]
Our input forms don't give any visual indications when a user tries submitting without `required` fields. 

When such submission is attempted could the missing fields be given a red border and the text "This field is required" be displayed

cc: @nairabhishek73

**Comment by nairabhishek73** [comment]
Yeah that'll be better. Could we use a lighter shade of red, an also apply the same red to the delete case option.
The current red is very jarring.

**Comment by ALOK9442** [comment]
Hey @fatchat sir, I wanna work on issues in this repo, Could you please help me with setting up the server locally? and is there any way to use the backend online rather than setting it locally as I am having troubles with airbyte while setting up the backend locally.

**Comment by fatchat** [comment]
hello @ALOK9442 , we do have an online backend and yes i can give you credentials if you demonstrate that you have a serious PR in progress

if not, then you'll need to set up the backend by reading whatever limited documentation is available :-(

**Comment by ALOK9442** [comment]
Hello @fatchat, I am working on this issue and I think I have solved it but to check if it is correct or not I need to check it by running the app and for that to run on local server I need backend up and running, I will be showing the code so that you can see if it is anyhow closer to the solution or not,

In the code I have defined validationError and used it..
![Screenshot 2024-04-04 015725](https://github.com/DalgoT4D/webapp/assets/104527572/4d6ea99b-6eef-4d36-aba7-3a669abe10cf)

**Comment by fatchat** [comment]
hi @ALOK9442 

is that the entire diff? if so it will not solve this issue... this is a hard issue, i doubt the solution is so short

you should take the time to set up the whole stack, it takes a while but it is good fun

**Comment by ALOK9442** [comment]
hey @fatchat ,
sir don't do this to me I don't wanna enjoy this fun, jokes apart,
could you please help me with setting up airbyte like exactly how would i set it up after installing and running it locally
