### ISSUE TITLE
RBAC invite: Invited user is added directly to user list before accepting invite.

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#876]
https://jam.dev/c/91c2c43b-3990-4204-b0e7-44f88334416c

UI testing org 6 on staging
User should be in pending invites

Probably because now this user is already in some list of previous users on staging?

**Comment by nairabhishek73** [comment]
Also invited user is able to access the org without acceppting invite.

**Comment by fatchat** [comment]
@nairabhishek73 this is correct, once an individual has set a login password for Dalgo they never need to do that again

**Comment by nairabhishek73** [comment]
Understood. That's fine but if I send an invite then there should be a criteria for the invitee to move from 'pending' to 'user' since this is org specific and not platform specific from the perspective of the person inviting.

They should move from 'pending' to 'user' only after the invitee ID has accessed the org once (via the email link or just opening the platform and seeing the org as an option in their dropdown of list of orgs.)

**Comment by fatchat** [comment]
the invitee is supposed to get an email telling them they've been added to a new org (and hopefully this happened)

so they get an email
and when they log in next
the new org appears in their list

there's nothing for them to do. we considered allowing them to reject the invitation but why would they do that this isn't a social site

(this has been standard since september ref https://github.com/DalgoT4D/DDP_backend/issues/324)

**Comment by nairabhishek73** [comment]
It informs the inviter of whether or not the invitee has opened the org page since receiving the invite.

**Comment by nairabhishek73** [comment]
Yes!
