### ISSUE TITLE
Error messaging on data statistics

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#941]
https://jam.dev/c/dcc79707-8ef0-4a31-bc6b-d631583c7569

In what situation would the try again button work? In the video you'll otice that I have no info on the problem and all i'm left to do is to keep hitting a button and hoping it works.

Ideally the user should be informed of the error and if try again doesn't work then be directed to support. 

Moreover what is the purpose of the try again button? Do we expect individual rows to fail to load? If try again is not expected to change anything then just do away with that button. they can click away and click on the table again, else they can hit refresh for the full statistics.

**Comment by Ishankoradia** [comment]
Sometimes, when people are running the same warehouse/table insights concurrently under same org. One of them might see "try again" because the insights are generated but it failed fetch. This is a super rare case (< 1%), at this point they might just hit "try again" & get the numbers magically.

But you are right for most of the cases, if an insight computation has failed hitting "try again" would just make it fail again. It wont do the user any good. 

We will remove that button. We will need to display some text there when it fails to fetch, i was thinking maybe "Hit refresh to try again" ?. @nairabhishek73

**Comment by nairabhishek73** [comment]
Yes that works. Instead of asking them to reach out to us can we make this a bit easier for them so that they hit a button and we're automatically notified of the problem?

**Comment by Ishankoradia** [comment]
@nairabhishek73 doesnt make sense to add customer support just for this. 
If we are adding a button that notifies us of the issue, it should be for entire Dalgo platform. 

We can tackle this a Dalgo feature instead of just data insights feature. 

For now we will just change the wording.

**Comment by mdshamoon** [comment]
This is fixed. @nairabhishek73 ready for testing
